version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: taskmanagerdb
    volumes:
      - mysql_data:/var/lib/mysql

  taskmanagerapi:
    build:
      context: .
      dockerfile: TaskManagerAPI/Dockerfile
    container_name: taskmanager-api
    ports:
      - "5000:80"
    depends_on:
      - mysql
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=server=mysql;port=3306;database=taskmanagerdb;user=root;password=pass123;

volumes:
  mysql_data: