version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: taskmanagerdb
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/init.sql

  taskmanagerapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskmanager-api
    ports:
      - "7154:80"
    depends_on:
      - mysql
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ConnectionStrings__DefaultConnection=server=mysql;port=3306;database=taskmanagerdb;user=root;password=pass123;